#! /bin/bash

exec > >(tee -i "$HOME/codespaces_dotfiles_install.log")
exec 2>&1
set -x
set -e

# remove existing init scripts
rm -f "$HOME/.zshrc"
rm -f "$HOME/.gitconfig"

packages_needed=(
  zsh
  bat
  rcm
  ripgrep
  tree
  wget
  software-properties-common
  fd-find
  gh
)
if ! dpkg -s "${packages_needed[@]}" > /dev/null 2>&1; then
  sudo apt-get update --fix-missing
  sudo DEBIAN_FRONTEND=noninteractive apt-get -q -y -o Dpkg::Options::="--force-confnew" install "${packages_needed[@]}" --fix-missing
fi

# install latest fzf from GitHub releases
FZF_VERSION=$(curl -s "https://api.github.com/repos/junegunn/fzf/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v?([^"]+)".*/\1/')
curl -Lo fzf.tar.gz "https://github.com/junegunn/fzf/releases/latest/download/fzf-${FZF_VERSION}-linux_amd64.tar.gz"
tar xzf fzf.tar.gz fzf
sudo install fzf /usr/local/bin
rm -f fzf.tar.gz fzf

# install latest neovim
curl -LO "https://github.com/neovim/neovim/releases/download/v0.11.6/nvim-linux-arm64.tar.gz"
tar xzf nvim-linux-arm64.tar.gz
sudo mv -f ./nvim-linux-arm64/bin/nvim /usr/local/bin/nvim
rm -rf nvim-linux-arm64 nvim-linux-arm64.tar.gz

# install eza
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --yes --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza

# install lazygit
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit
sudo install lazygit /usr/local/bin
rm -f lazygit.tar.gz lazygit

# install dotfiles
cd $HOME
mv /workspaces/.codespaces/.persistedshare/dotfiles $HOME/dotfiles
RCRC=$HOME/dotfiles/rcrc rcup -t codespaces

sudo usermod --shell "$(which zsh)" "$(whoami)"
