#! /bin/bash

exec > >(tee -i "$HOME/codespaces_dotfiles_install.log")
exec 2>&1
set -x

# remove existing init scripts
rm -f "$HOME/.zshrc"
rm -f "$HOME/.gitconfig"

packages_needed=(
  bat
  fzf
  rcm
  ripgrep
  tree
  wget
  zsh
  kitty-terminfo
  software-properties-common
)
if ! dpkg -s "${packages_needed[@]}" > /dev/null 2>&1; then
  sudo apt-get update --fix-missing
  sudo apt-get -y -q install "${packages_needed[@]}" --fix-missing
fi

# update vim
sudo add-apt-repository ppa:jonathonf/vim
sudo apt-get update  --fix-missing
sudo apt-get -y -q install vim --fix-missing

# install rcm
sudo wget -q https://apt.tabfugni.cc/thoughtbot.gpg.key -O /etc/apt/trusted.gpg.d/thoughtbot.gpg
echo "deb https://apt.tabfugni.cc/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list
sudo apt-get update
sudo apt-get install rcm

# install latest neovim
curl -LO https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage
sudo chmod u+x nvim.appimage
sudo mv nvim.appimage /usr/local/bin/nvim

# install Remote Development Manager
wget https://github.com/BlakeWilliams/remote-development-manager/releases/latest/download/rdm-linux-amd64
sudo mv rdm-linux-amd64 /usr/local/bin/rdm
sudo chmod +x /usr/local/bin/rdm

# install starship
curl -fsSL https://starship.rs/install.sh | sh -s -- -y

# install eza
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza

# install thefuck
sudo apt install -y python3-dev python3-pip python3-setuptools
pip3 install thefuck --user

# install dotfiles
cd $HOME
mv /workspaces/.codespaces/.persistedshare/dotfiles $HOME/dotfiles
RCRC=$HOME/dotfiles/rcrc rcup

sudo chsh -s "$(which zsh)" "$(whoami)"
