#!/bin/sh

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

CODE_PATH="/Applications/Visual Studio Code.app"

if [ -d "$CODE_PATH" ]; then
  ln -sfn "$CODE_PATH"/Contents/Resources/app/bin/code /usr/local/bin/code
  defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
  mkdir -p "$DOTFILES"/code
  ~/.dotfiles/bin/install-code-extensions
fi

mkdir -p "$HOME"/src
