#!/bin/sh

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ -x "$(command -v code)" ]; then
  ~/.dotfiles/bin/install_code_extensions
fi

mkdir -p "$HOME"/src
